---

#- name: Update apt cache  #title show ra cho coi
#  command: apt update

- name: Install meld
  become: yes
#  apt: name=nginx state=present
  apt:
    pkg: meld
    state: present

#how to check version meld