---

- hosts: all
  become: yes
  roles:
    - base
    # - htop
    # - pydf
    # - tmux
    # - zsh
    # - zsh-autosuggestions
    # - postgresql
    # # - chrome
    # - git
    # - meld
    - mysql
    - php
    # - vlc