---

- hosts: all
  become: yes
  roles:
    - base
    # - chrome
    # - git
    # - htop
    # - meld
    # - mysql
    # - php
    # - postgresql
    # - pydf
    - sublime
    # - tmux
    # - vlc
    # - zsh
    # - zsh-autosuggestions