---

# - name: Install RVM
#   import_tasks: 'rvm.yml'
#   become: yes
#   become_user: '{{ rvm1_user }}'

# - name: Install Ruby and Gems
#   import_tasks: 'rubies.yml'
#   become: yes
#   become_user: '{{ rvm1_user }}'

# - name: Install rails through Gem
#   # environment:
#   #   PATH: /usr/local/rvm/gems/ruby-2.3.1/bin:/usr/local/rvm/gems/ruby-2.3.1@global/bin:/usr/local/rvm/rubies/ruby-2.3.1/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/rvm/bin
#   #   GEM_PATH: /usr/local/rvm/gems/ruby-2.3.1:/usr/local/rvm/gems/ruby-2.3.1@global
#   #   # PATH: "/home/vagrant/.rvm/rubies/ruby-2.3.1/bin: {{ ansible_env.PATH }}"
#   become: no
#   gem:
#     name: rails
#     version: 5.1.2
#     state: present
#     user_install: no
#     executable: '{{ rvm1_install_path }}/rubies/{{ rvm1_default_ruby_version }}/bin/gem'


# - name: Cloning demo-rails-app
#   become: no
#   git:
#     repo: https://github.com/dhhiep/demo-rails-app.git
#     dest: ~/demo-rails-app
#     update: no

- name: Install rails
  become: yes
  become_user: '{{ rvm1_user }}'
  environment:
    PATH: "/home/vagrant/.rvm/gems/ruby-2.3.1/bin:\
            /home/vagrant/.rvm/gems/ruby-2.3.1@global/bin:\
            /home/vagrant/.rvm/rubies/ruby-2.3.1/bin:\
            /home/vagrant/.rvm/bin:\
            {{ lookup('env', 'PATH') }}"
    GEM_PATH: "/home/vagrant/.rvm/gems/ruby-2.3.1:\
                /home/vagrant/.rvm/gems/ruby-2.3.1@global"
  command: 'bundle'
  args:
    chdir: ~/demo-rails-app
  # register: result

# - debug:
#     var: result
    # verbosity: 2

