---

#- name: Update apt cache  #title show ra cho coi
#  command: apt update
- name: "apt | ensure sublime linux signing key present"
  apt_key: url=https://download.sublimetext.com/sublimehq-pub.gpg state=present


- name: Add  sublime repo
  copy:
    content: "deb https://download.sublimetext.com/ apt/stable/"
    dest: /etc/apt/sources.list.d/sublime-text.list
    owner: root
    group: root
    mode: 644
    force: no

- name: apt-get update
  apt:
    update_cache: yes

- name: Install sublime
#  apt: name=nginx state=present
  apt:
    pkg: sublime-text
    state: present

  # thieu cbi 1 file chua config, xog sau do copy vao thu muc setting file bla bla....
