---
# WordPress
- name: Get WordPress checksum
  uri:
    url: https://wordpress.org/latest.zip.sha1
    return_content: true
  register: wp_checksum

# WordPress
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/wordpress.zip
    checksum: "sha1:{{wp_checksum.content}}"

- name: Install required tools
  apt:
    name={{ item }} state=present
  with_items:
    - unzip

- name: Unzip WordPress
  unarchive:
    src: /tmp/wordpress.zip
    dest: /tmp
    copy: no
    creates: /tmp/wordpress/wp-settings.php

- name: Create project folder
  file:
     dest: /var/www/book.example.com
     state: directory

- name: Copy WordPress files
  command: cp -a /tmp/wordpress/. /var/www/book.example.com
  creates: /var/www/book.example.com/wp-settings.php

- name: Create WordPress MySQL database
  mysql_db:
    name: wordpress
    state: present

- name: Create User Wordpress
  mysql_user: name=wordpress host=localhost password={{ wordpress_pass }} priv=wordpress.*:ALL

- name: Create wp-config
  template:
    src: wp-config.php
    dest: /var/www/book.example.com/wp-config.php
